version: '3.8'
services:
  wordpress:
    build: ./path_to_wordpress_dockerfile
    depends_on:
      - db
    ports:
      - "8080:80"

  joomla:
    build: ./path_to_joomla_dockerfile
    depends_on:
      - db
    ports:
      - "8090:80"

  db:
    build: ./path_to_mysql_dockerfile
    environment:
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    build: ./path_to_nginx_dockerfile
    ports:
      - "80:80"
    depends_on:
      - wordpress
      - joomla

volumes:
  db_data:

